### PR TITLE
add icon support

### PR DESCRIPTION
**Pull request by mattveraldi**
Hi,

Thank you for this great extension! 🎉 

I added the **icon support**, a feature that I needed myself and that I saw being also a feature request #33 
I only implemented the icon part of the feature, because **the color part is implemented by this PR #28** 

Let me know if I need to do any changes, I am happy to contribute as efficiently as possible 😄

### CODE REVIEW

**Review by EthanSK — APPROVED** [review]
looks good!

**Comment by MartyUtloo** [comment]
How come the icon support was not added to the extension?

**Comment by EthanSK** [comment]
because it doesn't work. VScode API is terrible and broken and doesn't abide by the official documentation.

**Comment by EthanSK** [comment]
tbh it's a miracle this extension even works as is, with all the hacks it implements

**Pull request merged**
